version: '2'

services:
  async_proxy:
    build: .
    container_name: async_proxy
    volumes:
      - .:/app
    command: ["python", "-m", "proxy"]
    environment:
      HTTP_PROXY_PORT: 8080
    ports:
      - "8080:8080"
